[profile.default]
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}, { access = "read", path = "./out"}]
libs = ["lib"]
out = "out"
# solc_version = "0.8.26"
auto_detect_solc = true
src = "src"
via_ir = false

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
