[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
ffi = true
optimizer = true
optimizer_runs = 300

[rpc_endpoints]
unichain-sepolia="${RPC_URL_UNICHAIN_SEPOLIA}"
